### ISSUE TITLE
Rename option callRighAway

### ISSUE THREAD

**Issue by shuvo-me** [p32929/use-megamind#1]
I think callRighAway is not an understandable name for the option. It can be renamed as callOnMount or callImmedietly or something else. Thanks

![image](https://github.com/p32929/use-megamind/assets/61267686/23823a2e-5557-4aee-b53e-de3a1baa4811)

**Comment by p32929** [comment]
yes, I figured out already but thanks for pointing out ^_^

**Comment by p32929** [comment]
yes, I figured out already but thanks for pointing out ^_^ 
Will be updated soon

**Comment by p32929** [comment]
Fixed the issue on v1.0.4

closing the issue
